// website/src/components/ReadingProgress/index.tsx
import React, {useEffect, useState} from 'react';

export default function ReadingProgress(): React.JSX.Element {
  const [width, setWidth] = useState(0);

  useEffect(() => {
    function onScroll() {
      const {scrollTop, scrollHeight, clientHeight} = document.documentElement;
      const total = scrollHeight - clientHeight;
      setWidth(total > 0 ? (scrollTop / total) * 100 : 0);
    }
    window.addEventListener('scroll', onScroll, {passive: true});
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  return <div className="reading-progress" style={{width: `${width}%`}} />;
}

// docs/.vitepress/theme/components/ReadingProgress.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'

const width = ref(0)

function onScroll() {
  const { scrollTop, scrollHeight, clientHeight } = document.documentElement
  const total = scrollHeight - clientHeight
  width.value = total > 0 ? (scrollTop / total) * 100 : 0
}

onMounted(() => {
  window.addEventListener('scroll', onScroll, { passive: true })
})

onUnmounted(() => {
  window.removeEventListener('scroll', onScroll)
})
</script>

<template>
  <div class="reading-progress" :style="{ width: `${width}%` }" />
</template>
